name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop  # Trigger on push to the develop branch

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checkout the code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Set up Node.js version 16

      - name: Install Dependencies
        run: npm install  # Install project dependencies

      - name: Build Website
        run: npm run build  # Build the static website using Parcel

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist  # Path to the build output (dist folder)

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest  # Use Ubuntu runner
    needs: build  # This job depends on the 'build' job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checkout the code

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Deploy the build output to GitHub Pages
