name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Static Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run build # Assuming Parcel is set up to build the website

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Assuming the build output is in the dist folder

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
